import cors from 'cors';
import crypto from 'crypto';
import express from 'express';
import { mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import multer from 'multer';

const app=express(), PORT=Number(process.env.PORT||5000), LIMIT=25*1024*1024, OTP_MS=300000, SESSION_MS=28800000;
const DB_PATH=process.env.SAKSHYA_DB_PATH||join(process.cwd(),'data','sakshya.sqlite');
const SECRET=process.env.SAKSHYA_SESSION_SECRET||'sakshya-demo-session-secret-change-in-production';
const R={IO:'Investigating Officer',FA:'Forensic Analyst',SA:'Senior Authority',CV:'Court Viewer',AD:'System Admin'};
const READ=[R.IO,R.FA,R.SA,R.CV,R.AD], records=new Map();
mkdirSync(dirname(DB_PATH),{recursive:true}); const db=new DatabaseSync(DB_PATH);
db.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS evidence_records(id TEXT PRIMARY KEY,record_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_events(id TEXT PRIMARY KEY,evidence_id TEXT NOT NULL REFERENCES evidence_records(id) ON DELETE CASCADE,event_json TEXT NOT NULL,ordinal INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_audit_events_evidence ON audit_events(evidence_id,ordinal);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,name TEXT NOT NULL,badge TEXT NOT NULL,role TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS auth_sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires_at INTEGER NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS registered_devices(id TEXT PRIMARY KEY,label TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS source_devices(id TEXT PRIMARY KEY,device_type TEXT NOT NULL,organisation_unit TEXT NOT NULL,status TEXT NOT NULL,trusted_reference TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,created_by TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS network_events(id TEXT PRIMARY KEY,evidence_id TEXT,actor_id TEXT,attempted_action TEXT NOT NULL,context_json TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_network_events_evidence ON network_events(evidence_id,created_at);
CREATE TABLE IF NOT EXISTS verification_tokens(token_hash TEXT PRIMARY KEY,evidence_id TEXT NOT NULL,expires_at INTEGER NOT NULL,revoked_at TEXT,created_at TEXT NOT NULL,created_by TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS physical_evidence_tags(physical_tag_id TEXT PRIMARY KEY,evidence_id TEXT NOT NULL,seal_identifier TEXT NOT NULL,location TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,created_by TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS synced_actions(action_id TEXT PRIMARY KEY,evidence_id TEXT NOT NULL,actor_id TEXT NOT NULL,action_type TEXT NOT NULL,payload_json TEXT NOT NULL,sequence_number INTEGER NOT NULL,processed_at TEXT NOT NULL);`);
app.set('trust proxy',process.env.SAKSHYA_TRUST_PROXY==='true'?1:false); // Enable only behind one known reverse proxy.
app.use(cors());app.use(express.json({limit:'1mb'})); const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:LIMIT}});
const clean=(v,f='')=>String(v??f).trim(), hash=v=>crypto.createHash('sha256').update(v).digest('hex'), iso=()=>new Date().toISOString();
const labels={UPLOADED:'Evidence uploaded',VIEWED:'Evidence viewed',TRANSFERRED:'Custody transferred',EDITED:'Evidence edited',COURT_ACCESSED:'Court access granted',VERIFIED:'Integrity verified',SECURITY_INCIDENT:'Security incident recorded',INCIDENT_REVIEWED:'Security incident reviewed'};
const labelKeys=new Map(Object.entries(labels).map(([k,v])=>[v,k]));
function pass(p,s=crypto.randomBytes(16).toString('base64url')){return `scrypt$${s}$${crypto.scryptSync(p,s,64).toString('base64url')}`;}
function matches(p,stored){const [,s,e]=String(stored).split('$');if(!s||!e)return false;const a=crypto.scryptSync(p,s,64).toString('base64url');return a.length===e.length&&crypto.timingSafeEqual(Buffer.from(a),Buffer.from(e));}
function seed(){const x=[['usr-investigator','investigator','demo-investigator-2026','Asha Mehra','IO-1042',R.IO],['usr-analyst','analyst','demo-analyst-2026','Ravi Sen','FA-2088',R.FA],['usr-authority','authority','demo-authority-2026','Nisha Kapoor','SA-3011',R.SA],['usr-court','court','demo-court-2026','Court Registry Viewer','CV-4007',R.CV],['usr-admin','admin','demo-admin-2026','System Administrator','AD-5003',R.AD]];const q=db.prepare('INSERT OR IGNORE INTO users(id,username,password_hash,name,badge,role,active,created_at) VALUES(?,?,?,?,?,?,1,?)');x.forEach(([id,u,p,n,b,r])=>q.run(id,u,pass(p),n,b,r,iso()));}
const publicUser=u=>({id:u.id,username:u.username,name:u.name,badge:u.badge,role:u.role,active:Boolean(u.active)});
const sig=x=>crypto.createHmac('sha256',SECRET).update(x).digest('base64url');
function session(u){const p=Buffer.from(JSON.stringify({sid:crypto.randomUUID(),uid:u.id,role:u.role,exp:Date.now()+SESSION_MS})).toString('base64url'),t=`${p}.${sig(p)}`;db.prepare('INSERT INTO auth_sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)').run(hash(t),u.id,Date.now()+SESSION_MS,iso());return t;}
function auth(required=true){return(req,res,next)=>{const t=(req.headers.authorization||'').startsWith('Bearer ')?req.headers.authorization.slice(7):'';if(!t)return required?res.status(401).json({error:'Authentication is required.'}):next();const [p,s]=t.split('.');if(!p||!s||Buffer.from(s).length!==Buffer.from(sig(p)).length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(sig(p))))return res.status(401).json({error:'Invalid or expired session token.'});let c;try{c=JSON.parse(Buffer.from(p,'base64url').toString())}catch{return res.status(401).json({error:'Invalid session token.'})}const z=db.prepare('SELECT user_id,expires_at FROM auth_sessions WHERE token_hash=?').get(hash(t));const u=z&&z.expires_at>=Date.now()&&c.exp>=Date.now()?db.prepare('SELECT * FROM users WHERE id=? AND active=1').get(z.user_id):null;if(!u||u.role!==c.role)return res.status(401).json({error:'Invalid or expired session token.'});req.actor=publicUser(u);next();};}
function allow(...roles){return[auth(),(req,res,next)=>{if(roles.includes(req.actor.role))return next();const evidenceId=req.params?.id||null;captureNetwork(req,evidenceId,'DENIED_ROLE_ACTION','HIGH');const r=evidenceId&&records.get(evidenceId);if(r){append(r,{action:'SECURITY_INCIDENT',...actor(req),details:`Denied role action: ${req.method} ${req.path}.`,location:'Not voluntarily shared'});save(r)}return res.status(403).json({error:'Your role is not authorised for this action.',requiredRoles:roles})}];}
const actor=(req,f={actor:'Authorised Officer',badge:'—',role:'Custody Officer'})=>req.actor?{actor:req.actor.name,badge:req.actor.badge,role:req.actor.role}:f;
function networkHistory(evidenceId){return db.prepare('SELECT attempted_action,context_json,created_at FROM network_events WHERE evidence_id=? ORDER BY created_at').all(evidenceId).map(x=>({attemptedAction:x.attempted_action,timestamp:x.created_at,...JSON.parse(x.context_json)}));}
function voluntaryLocation(req){const b=req.body||{};return b.locationConsent===true||b.locationConsent==='true'?clean(b.locationContext||b.authorisedActionLocation||b.location,'Not voluntarily shared'):'Not voluntarily shared';}
function requestTrace(req,evidenceId,attemptedAction,severity='MEDIUM'){const ip=clean(req.ip||req.socket.remoteAddress,'Unavailable').replace(/^::ffff:/,'');const local=ip==='::1'||ip==='127.0.0.1'||ip.startsWith('10.')||ip.startsWith('192.168.');return{sourceNetwork:ip,deviceContext:clean(req.headers['user-agent'],'Unavailable'),locationContext:voluntaryLocation(req),timestamp:iso(),evidenceId:evidenceId||null,actor:req.actor?{id:req.actor.id,name:req.actor.name,role:req.actor.role}:null,attemptedAction,severity,networkOrigin:local?'Local/private network context':'Approximate network-origin context for lawful authorised investigation.',approximate:{available:false,confidence:'NONE',note:local?'Private/local address; public geolocation is not applicable.':'No external geolocation service is configured; no city, GPS, ISP or identity is inferred.'}};}
function captureNetwork(req,evidenceId,attemptedAction,severity='MEDIUM'){const c=requestTrace(req,evidenceId,attemptedAction,severity);db.prepare('INSERT INTO network_events(id,evidence_id,actor_id,attempted_action,context_json,created_at) VALUES(?,?,?,?,?,?)').run(crypto.randomUUID(),evidenceId||null,req.actor?.id||null,attemptedAction,JSON.stringify(c),c.timestamp);return c;}
function safeTrace(trace,viewer){if(viewer?.role===R.AD||viewer?.role===R.SA)return trace;return{...trace,sourceNetwork:'Redacted',deviceContext:'Redacted',locationContext:trace.locationContext==='Not voluntarily shared'?'Not voluntarily shared':'Voluntarily shared (redacted)'};}
function safeIncident(value,viewer){const trace=value.networkOriginContext||{sourceNetwork:value.sourceNetwork,deviceContext:value.deviceContext||value.deviceMetadata,locationContext:value.locationContext||value.authorisedActionLocation||'Not voluntarily shared'};const safe=safeTrace(trace,viewer);return{...value,sourceNetwork:safe.sourceNetwork,deviceContext:safe.deviceContext,locationContext:safe.locationContext,deviceMetadata:undefined,authorisedActionLocation:undefined,networkOriginContext:safe};}
function risk(r){const p=provenanceRisk(r),i=integrity(r),reasons=[];let score=0;if(!i.evidenceHashValid){score+=45;reasons.push('Current evidence hash differs from its sealed SHA-256 hash.')}if(!i.auditChainValid){score+=35;reasons.push('Cryptographic audit-chain verification failed.')}if(p.status==='REVIEW_REQUIRED'){score+=15;reasons.push('Source provenance requires review.')}if((r.securityIncidents||[]).length){score+=Math.min(20,(r.securityIncidents||[]).length*5);reasons.push('Blocked custody-transfer attempt(s) were recorded.')}if(p.flags?.some(x=>x.includes('device'))){score+=10;reasons.push('Evidence source device is unknown or inactive.')}if((r.securityIncidents||[]).some(x=>x.status==='OPEN'||x.status==='UNDER_REVIEW')){score+=10;reasons.push('An unresolved security incident remains.')}if((r.auditChain||[]).some(e=>{const h=new Date(e.at).getUTCHours();return h<6||h>=20;})){score+=5;reasons.push('Off-hours custody activity is present.')}score=Math.min(100,score);return{score,band:score>=80?'CRITICAL':score>=55?'HIGH':score>=25?'MEDIUM':'LOW',reasons:reasons.length?reasons:['No configured rule-based risk factors are currently active.'],method:'Deterministic rule-based / explainable score; not machine learning.'};}
function provenanceRisk(r){return r.provenance||{status:'SOURCE_UNKNOWN',flags:['source hash unavailable']};}
function sourceDevice(id){return id?db.prepare('SELECT * FROM source_devices WHERE id=?').get(id):null;}
function save(r){const{auditChain,...stored}=r;db.prepare('INSERT INTO evidence_records(id,record_json) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET record_json=excluded.record_json').run(r.id,JSON.stringify(stored));db.prepare('DELETE FROM audit_events WHERE evidence_id=?').run(r.id);const q=db.prepare('INSERT INTO audit_events(id,evidence_id,event_json,ordinal) VALUES(?,?,?,?)');r.auditChain.forEach((e,i)=>q.run(e.id,r.id,JSON.stringify(e),i));}
function load(){for(const row of db.prepare('SELECT id,record_json FROM evidence_records').all()){const r=JSON.parse(row.record_json);r.auditChain=db.prepare('SELECT event_json FROM audit_events WHERE evidence_id=? ORDER BY ordinal').all(row.id).map(x=>JSON.parse(x.event_json));r.securityIncidents||=[];r.provenance||={status:'SOURCE_UNKNOWN',flags:['source hash unavailable']};records.set(r.id,r);}}
function append(r,o={}){const e={id:crypto.randomUUID(),action:labels[o.action]||o.action||labels.VIEWED,actor:clean(o.actor,'Authorised Officer'),badge:clean(o.badge,'—'),role:clean(o.role,'Custody Officer'),details:clean(o.details),at:iso(),location:clean(o.location,'Registered evidence facility'),previousHash:r.auditChain.at(-1)?.eventHash||null};e.eventHash=hash(JSON.stringify(e));r.auditChain.push(e);return e;}
function integrity(r){let p=null,b=null;for(const[i,e]of r.auditChain.entries()){const{eventHash,...unsigned}=e;if(e.previousHash!==p||hash(JSON.stringify(unsigned))!==eventHash){b=i;break}p=eventHash}const hv=r.originalHash===r.currentHash;return{valid:hv&&b===null,evidenceHashValid:hv,auditChainValid:b===null,brokenAtIndex:hv&&b===null?null:b??r.tamperBlockIndex??Math.max(r.auditChain.length-1,0)};}
function pub(r,viewer){const x=integrity(r),chain=r.auditChain.map((e,i)=>({index:i,action:labelKeys.get(e.action)||e.action,officer:e.actor,badge:e.badge,role:e.role,timestamp:e.at,details:e.details,location:e.location,eventHash:e.eventHash,hash:`sha256:${e.eventHash}`,previousHash:e.previousHash?`sha256:${e.previousHash}`:'GENESIS',verified:x.brokenAtIndex===null||i<x.brokenAtIndex,compromised:x.brokenAtIndex!==null&&i>=x.brokenAtIndex})),inc=(r.securityIncidents||[]).map(i=>safeIncident(i,viewer));return{id:r.id,docId:r.id,name:r.name,fileName:r.name,size:r.size,mimeType:r.mimeType,caseId:r.caseId,description:r.description,evidenceType:r.evidenceType,classification:r.classification,originalHash:r.originalHash,currentHash:r.currentHash,createdAt:r.createdAt,custodyHolder:r.custodyHolder,assignedOfficerId:r.assignedOfficerId||null,tampered:!x.valid,tamperBlockIndex:x.brokenAtIndex,status:x.valid?'valid':'compromised',valid:x.valid,chainLength:chain.length,lastActivity:chain.at(-1)?.timestamp||r.createdAt,chain,timeline:[...chain].reverse(),securityIncidents:inc,provenance:r.provenance,auditChainValid:x.auditChainValid,auditChainHead:r.auditChain.at(-1)?.eventHash||null,networkOriginContext:networkHistory(r.id).map(n=>safeTrace(n,viewer)),riskScore:risk(r),anomalyFlags:{offHoursActivity:chain.some(e=>{const h=new Date(e.timestamp).getUTCHours();return h<6||h>=20}),hashMismatch:!x.evidenceHashValid,brokenAuditChain:!x.auditChainValid,intrusionAttempt:inc.length>0}};}
function record(req,res){const r=records.get(req.params.id);if(!r){res.status(404).json({error:'Evidence not found.'});return null}return r;}
function readable(req,res,next){const r=record(req,res);if(!r)return;if(req.actor.role===R.IO&&r.assignedOfficerId&&r.assignedOfficerId!==req.actor.id)return res.status(403).json({error:'Investigating Officers may view only assigned evidence.'});req.record=r;next();}
function provenance(m,h){const st=clean(m.sourceType,'manual upload'),id=clean(m.sourceSystemDeviceId),sh=clean(m.officialSourceHash),sr=clean(m.sourceSignatureReference),at=clean(m.attestationStatement),f=[],d=sourceDevice(id);if(!id)f.push('unregistered source device');else if(!d)f.push('unknown source device');else if(d.status!=='ACTIVE')f.push('inactive source device');if(!sh&&!sr)f.push('source hash unavailable');if(sh&&sh!==h)f.push('source hash mismatch');if(!at)f.push('missing uploader attestation');if(!clean(m.authorisedActionLocation))f.push('upload outside authorised location');const trusted=st.toLowerCase()!=='manual upload'&&!!d&&d.status==='ACTIVE'&&!!(sh||sr)&&(!d.trusted_reference||d.trusted_reference===sh||d.trusted_reference===sr);if(d?.trusted_reference&&d.trusted_reference!==sh&&d.trusted_reference!==sr)f.push('registered device reference mismatch');return{status:sh&&sh!==h||f.some(x=>x.includes('unknown')||x.includes('inactive')||x.includes('mismatch'))?'REVIEW_REQUIRED':trusted&&!f.length?'SOURCE_VERIFIED':f.includes('missing uploader attestation')?'REVIEW_REQUIRED':'SOURCE_UNKNOWN',flags:f,uploader:{name:clean(m.officerName,'Unknown uploader'),badge:clean(m.officerBadge,'Not provided'),role:clean(m.officerRole,'Not provided')},attestationStatement:at||'Not provided',sourceSystemDeviceId:id||'Not provided',sourceType:st,officialSourceHash:sh||null,sourceSignatureReference:sr||null,authorisedActionLocation:clean(m.authorisedActionLocation)||'Not voluntarily provided',registeredDevice:d?{id:d.id,type:d.device_type,status:d.status,organisationUnit:d.organisation_unit}:null};}
function create({id,file,metadata:m={},user}){const bytes=file?.buffer||Buffer.from(JSON.stringify({id,caseId:m.caseId,description:m.description})),h=hash(bytes),u=user||{name:clean(m.officerName,'Forensic Officer'),badge:m.officerBadge,role:m.officerRole||R.IO},meta={...m,officerName:u.name,officerBadge:u.badge,officerRole:u.role},r={id,name:file?.originalname||clean(m.fileName,`${id}_evidence_record`),size:file?.size||bytes.length,mimeType:file?.mimetype||clean(m.mimeType,'application/octet-stream'),caseId:clean(m.caseId,'CASE/UNASSIGNED'),description:clean(m.description,'Registered evidence record.'),evidenceType:clean(m.evidenceType,'Digital Document'),classification:clean(m.classification,'Sensitive'),originalHash:h,currentHash:h,createdAt:iso(),custodyHolder:u.name,assignedOfficerId:user?.id||null,tamperBlockIndex:null,pendingTransfer:null,securityIncidents:[],provenance:provenance(meta,h),auditChain:[]};append(r,{action:'UPLOADED',actor:u.name,badge:u.badge,role:u.role,details:`${r.description} SHA-256 evidence hash sealed: ${h}`,location:m.location||'National Evidence Grid · Intake'});append(r,{action:'VIEWED',actor:'SAKSHYA Provenance Engine',badge:'SYSTEM-PROV',role:'Source Provenance Assessment',details:`Provenance status: ${r.provenance.status}. Flags: ${r.provenance.flags.join(', ')||'none'}.`,location:r.provenance.authorisedActionLocation});return r;}
function verify(r,req){const before=integrity(r);captureNetwork(req,r.id,before.valid?'EVIDENCE_VERIFICATION':'FAILED_CHAIN_VERIFICATION',before.valid?'LOW':'HIGH');append(r,{action:'VERIFIED',...actor(req,{actor:'Verification engine',badge:'SYSTEM-01',role:'Integrity Monitor'}),details:before.valid?'SHA-256 hash and audit chain verified.':'Integrity verification failed.',location:'National Evidence Grid'});save(r);return{...pub(r,req.actor),valid:before.valid,brokenAtIndex:before.brokenAtIndex,message:before.valid?'Evidence integrity verified.':'Evidence integrity compromised.'};}
function issueVerifier(r,actorId,reportTime){const expiresAt=Date.now()+86400000,payload=Buffer.from(JSON.stringify({evidenceId:r.id,caseId:r.caseId,reportGeneratedAt:reportTime,exp:expiresAt,jti:crypto.randomUUID()})).toString('base64url'),token=`${payload}.${sig(payload)}`;db.prepare('INSERT INTO verification_tokens(token_hash,evidence_id,expires_at,revoked_at,created_at,created_by) VALUES(?,?,?,?,?,?)').run(hash(token),r.id,expiresAt,null,reportTime,actorId||'SYSTEM-REPORT');return{token,verificationUrl:`/api/public/verify/${token}`,expiresAt:new Date(expiresAt).toISOString(),signed:true,publicSafe:true};}
function report(r,viewer){const generatedAt=iso(),qrVerification=issueVerifier(r,viewer?.id,generatedAt),x=integrity(r),p=pub(r,viewer);return{reportType:'Sakshya Court-Ready Forensic Evidence Report',generatedAt,evidence:p,integrityAssessment:{evidenceHashValid:x.evidenceHashValid,auditChainValid:x.auditChainValid,auditChainBrokenAt:x.brokenAtIndex,overallValid:x.valid},anomalyFlags:p.anomalyFlags,securityIncidents:p.securityIncidents,provenance:r.provenance,qrVerification,attestation:'This report is generated from SQLite evidence records and its cryptographically linked audit chain.'};}
function incident(r,req,action){const network=captureNetwork(req,r.id,action,'HIGH'),i={id:crypto.randomUUID(),rule:'INVALID_TRANSFER_OTP',attemptedAction:action,summary:'Unauthorised custody transfer was blocked because the submitted confirmation code was invalid.',status:'OPEN',timestamp:iso(),sourceNetwork:network.sourceNetwork,deviceContext:network.deviceContext,locationContext:network.locationContext,severity:'HIGH',networkOriginContext:network};r.securityIncidents.push(i);append(r,{action:'SECURITY_INCIDENT',...actor(req,{actor:'SAKSHYA Security Monitor',badge:'SYSTEM-SEC',role:'Intrusion Traceability'}),details:`${i.rule}: ${i.summary} Incident ${i.id}.`,location:i.locationContext});save(r);}
const id=v=>clean(v)||`DOC-2026-${Math.floor(10000+Math.random()*89999)}`;

app.post('/api/auth/login',(req,res)=>{const u=clean(req.body?.username).toLowerCase(),p=String(req.body?.password||'');if(!u||!p)return res.status(400).json({error:'username and password are required.'});const user=db.prepare('SELECT * FROM users WHERE username=? AND active=1').get(u);if(!user||!matches(p,user.password_hash))return res.status(401).json({error:'Invalid username or password.'});const token=session(user);res.json({token,tokenType:'Bearer',expiresAt:new Date(Date.now()+SESSION_MS).toISOString(),user:publicUser(user)});});
app.get('/api/auth/me',auth(),(req,res)=>res.json({user:req.actor}));
app.get('/api/health',(_q,res)=>res.json({ok:true,service:'Sakshya API',storage:'SQLite',uploadLimitBytes:LIMIT,documentCount:records.size}));
app.get('/api/documents',...allow(...READ),(req,res)=>res.json([...records.values()].filter(r=>req.actor.role!==R.IO||!r.assignedOfficerId||r.assignedOfficerId===req.actor.id).map(pub)));
app.post('/api/documents/upload',...allow(R.IO),(req,res)=>{const x=id(req.body?.docId);if(records.has(x))return res.status(409).json({error:`Document ${x} already exists.`});const r=create({id:x,metadata:req.body||{},user:req.actor});records.set(x,r);save(r);res.status(201).json(pub(r));});
app.get('/api/documents/:id/chain',...allow(...READ),readable,(req,res)=>res.json(pub(req.record)));
app.post('/api/documents/:id/verify',...allow(R.FA,R.CV),readable,(req,res)=>res.json(verify(req.record,req)));
app.post('/api/documents/:id/action',...allow(R.IO,R.SA),readable,(req,res)=>{const r=req.record,b=req.body||{},a=clean(b.action).toUpperCase();if(!['VIEWED','TRANSFERRED','EDITED','COURT_ACCESSED'].includes(a))return res.status(400).json({error:'Action must be VIEWED, TRANSFERRED, EDITED, or COURT_ACCESSED.'});const from=clean(b.fromOfficer||req.actor.name),to=clean(b.toOfficer);if(a==='TRANSFERRED'){if(!from||!to||!/^\\d{4}$/.test(clean(b.fromOtp))||!/^\\d{4}$/.test(clean(b.toOtp))){incident(r,req,'DUAL_CONFIRMATION_CUSTODY_TRANSFER');return res.status(403).json({error:'Custody transfer blocked: invalid dual-confirmation OTP.',evidence:pub(r)});}r.custodyHolder=to;}append(r,{action:a,...actor(req),details:clean(b.details,'Custody action recorded.'),location:b.location});save(r);res.status(201).json(pub(r));});
app.post('/api/documents/:id/simulate-tamper',...allow(R.SA),readable,(req,res)=>{const r=req.record,n=Number(req.body?.blockIndex);if(!Number.isInteger(n)||!r.auditChain[n])return res.status(400).json({error:'blockIndex must point to an existing chain block.'});r.auditChain[n].details=clean(req.body?.fakeData,'Evidence data modified outside the custody workflow.');r.currentHash=hash(`${r.currentHash}:tampered:${Date.now()}`);r.tamperBlockIndex=n;save(r);res.json(pub(r));});
app.get('/api/documents/:id/report',...allow(R.FA,R.CV,R.SA),readable,(req,res)=>res.json(report(req.record,req.actor)));
app.post('/api/evidence/upload',...allow(R.IO),upload.single('file'),(req,res)=>{if(!req.file)return res.status(400).json({error:'Please select one evidence file in the "file" field.'});const x=id(req.body?.docId);if(records.has(x))return res.status(409).json({error:`Document ${x} already exists.`});const r=create({id:x,file:req.file,metadata:req.body||{},user:req.actor});records.set(x,r);save(r);res.status(201).json(pub(r));});
app.get('/api/evidence/:id',...allow(...READ),readable,(req,res)=>res.json(pub(req.record,req.actor)));
app.post('/api/evidence/:id/verify',...allow(R.FA,R.CV),readable,(req,res)=>res.json(verify(req.record,req)));
app.post('/api/evidence/:id/transfer/request-otp',...allow(R.IO,R.SA),readable,(req,res)=>{const r=req.record,to=clean(req.body?.recipient);if(!to)return res.status(400).json({error:'A recipient is required.'});const otp=crypto.randomInt(0,1000000).toString().padStart(6,'0');r.pendingTransfer={recipient:to,otpHash:hash(otp),expiresAt:Date.now()+OTP_MS};append(r,{action:'VIEWED',...actor(req),details:`Transfer to ${to} requires OTP verification.`});save(r);res.json({message:'OTP generated. It expires in 5 minutes.',otp,expiresAt:new Date(r.pendingTransfer.expiresAt).toISOString()});});
app.post('/api/evidence/:id/transfer',...allow(R.IO,R.SA),readable,(req,res)=>{const r=req.record,p=r.pendingTransfer;if(!p)return res.status(400).json({error:'Request a transfer OTP before transferring custody.'});if(Date.now()>p.expiresAt){r.pendingTransfer=null;save(r);return res.status(400).json({error:'The transfer OTP has expired.'});}if(clean(req.body?.recipient)!==p.recipient||hash(clean(req.body?.otp))!==p.otpHash){incident(r,req,'OTP_VERIFIED_CUSTODY_TRANSFER');return res.status(401).json({error:'Custody transfer blocked: invalid OTP.',evidence:pub(r)});}r.custodyHolder=p.recipient;r.pendingTransfer=null;append(r,{action:'TRANSFERRED',...actor(req),details:`OTP-verified custody transfer to ${r.custodyHolder}.`});save(r);res.json(pub(r));});
app.post('/api/evidence/:id/tamper',...allow(R.SA),readable,(req,res)=>{const r=req.record,n=Math.max(0,r.auditChain.length-1);r.auditChain[n].details='Evidence hash deliberately altered for demonstration.';r.currentHash=hash(`${r.currentHash}:tampered:${Date.now()}`);r.tamperBlockIndex=n;save(r);res.json(pub(r));});
app.get('/api/evidence/:id/report',...allow(R.FA,R.CV,R.SA),readable,(req,res)=>res.json(report(req.record,req.actor)));
app.get('/api/evidence/:id/incidents',...allow(R.SA),readable,(req,res)=>res.json({evidenceId:req.record.id,securityIncidents:(req.record.securityIncidents||[]).map(i=>safeIncident(i,req.actor))}));
app.post('/api/evidence/:id/incidents/:incidentId/approve',...allow(R.SA),readable,(req,res)=>{const r=req.record,i=r.securityIncidents.find(x=>x.id===req.params.incidentId);if(!i)return res.status(404).json({error:'Security incident not found.'});i.status='APPROVED';i.reviewedAt=iso();i.reviewedBy=req.actor.name;append(r,{action:'INCIDENT_REVIEWED',...actor(req),details:`Security incident ${i.id} approved for follow-up.`,location:clean(req.body?.location,'Registered evidence facility')});save(r);res.json(pub(r));});
app.get('/api/admin/users',...allow(R.AD),(_q,res)=>res.json(db.prepare('SELECT id,username,name,badge,role,active,created_at FROM users ORDER BY username').all().map(u=>({...publicUser(u),createdAt:u.created_at}))));
app.post('/api/admin/users',...allow(R.AD),(req,res)=>{const b=req.body||{},u={id:crypto.randomUUID(),username:clean(b.username).toLowerCase(),name:clean(b.name),badge:clean(b.badge),role:b.role};if(!u.username||String(b.password||'').length<12||!u.name||!u.badge||!Object.values(R).includes(u.role))return res.status(400).json({error:'username, a password of at least 12 characters, name, badge, and a valid role are required.'});try{db.prepare('INSERT INTO users(id,username,password_hash,name,badge,role,active,created_at) VALUES(?,?,?,?,?,?,1,?)').run(u.id,u.username,pass(String(b.password)),u.name,u.badge,u.role,iso())}catch{return res.status(409).json({error:'That username is already in use.'})}res.status(201).json({user:u});});
app.get('/api/admin/devices',...allow(R.AD),(_q,res)=>res.json(db.prepare('SELECT * FROM registered_devices ORDER BY created_at DESC').all()));
app.post('/api/admin/devices',...allow(R.AD),(req,res)=>{const label=clean(req.body?.label);if(!label)return res.status(400).json({error:'A device label is required.'});const d={id:crypto.randomUUID(),label,status:'ACTIVE',created_at:iso(),created_by:req.actor.id};db.prepare('INSERT INTO registered_devices(id,label,status,created_at,created_by) VALUES(?,?,?,?,?)').run(d.id,d.label,d.status,d.created_at,d.created_by);res.status(201).json(d);});
app.get('/api/admin/source-devices',...allow(R.AD),(req,res)=>res.json(db.prepare('SELECT * FROM source_devices ORDER BY created_at DESC').all()));
app.post('/api/admin/source-devices',...allow(R.AD),(req,res)=>{const b=req.body||{},type=clean(b.deviceType),unit=clean(b.organisationUnit);if(!type||!unit||!['CCTV/DVR','forensic lab','mobile capture','document system'].includes(type))return res.status(400).json({error:'deviceType (CCTV/DVR, forensic lab, mobile capture, document system) and organisationUnit are required.'});const d={id:clean(b.deviceId)||crypto.randomUUID(),device_type:type,organisation_unit:unit,status:'ACTIVE',trusted_reference:clean(b.trustedHashOrSignatureReference)||null,created_at:iso(),updated_at:iso(),created_by:req.actor.id};try{db.prepare('INSERT INTO source_devices(id,device_type,organisation_unit,status,trusted_reference,created_at,updated_at,created_by) VALUES(?,?,?,?,?,?,?,?)').run(d.id,d.device_type,d.organisation_unit,d.status,d.trusted_reference,d.created_at,d.updated_at,d.created_by)}catch{return res.status(409).json({error:'Source device ID already exists.'})}res.status(201).json(d);});
app.patch('/api/admin/source-devices/:id',...allow(R.AD),(req,res)=>{const old=sourceDevice(req.params.id),b=req.body||{};if(!old)return res.status(404).json({error:'Source device not found.'});const status=clean(b.status,old.status);if(!['ACTIVE','INACTIVE'].includes(status))return res.status(400).json({error:'status must be ACTIVE or INACTIVE.'});db.prepare('UPDATE source_devices SET device_type=?,organisation_unit=?,status=?,trusted_reference=?,updated_at=? WHERE id=?').run(clean(b.deviceType,old.device_type),clean(b.organisationUnit,old.organisation_unit),status,clean(b.trustedHashOrSignatureReference,old.trusted_reference)||null,iso(),old.id);res.json(sourceDevice(old.id));});
app.post('/api/evidence/:id/incidents/:incidentId/status',...allow(R.SA),readable,(req,res)=>{const i=req.record.securityIncidents.find(x=>x.id===req.params.incidentId),status=clean(req.body?.status).toUpperCase(),reason=clean(req.body?.reason);if(!i)return res.status(404).json({error:'Security incident not found.'});if(!['UNDER_REVIEW','RESOLVED','DISMISSED'].includes(status)||!reason)return res.status(400).json({error:'status must be UNDER_REVIEW, RESOLVED, or DISMISSED and reason is required.'});i.status=status;i.review={reviewer:req.actor.name,badge:req.actor.badge,role:req.actor.role,at:iso(),reason};append(req.record,{action:'INCIDENT_REVIEWED',...actor(req),details:`Incident ${i.id} changed to ${status}: ${reason}`,location:clean(req.body?.location,'Registered evidence facility')});captureNetwork(req,req.record.id,`INCIDENT_${status}`);save(req.record);res.json(pub(req.record));});
app.post('/api/evidence/:id/verification-token',...allow(R.FA,R.SA),(req,res)=>{const r=record(req,res);if(!r)return;const ttl=Math.min(Math.max(Number(req.body?.ttlSeconds||86400),60),604800),token=crypto.randomBytes(32).toString('base64url');db.prepare('INSERT INTO verification_tokens(token_hash,evidence_id,expires_at,revoked_at,created_at,created_by) VALUES(?,?,?,?,?,?)').run(hash(token),r.id,Date.now()+ttl*1000,null,iso(),req.actor.id);append(r,{action:'VIEWED',...actor(req),details:'Court verification token issued. No evidence content is embedded.'});save(r);res.status(201).json({verificationToken:token,expiresAt:new Date(Date.now()+ttl*1000).toISOString(),verificationUrl:`/api/public/verify/${token}`,qrVerification:{tokenExpirySeconds:ttl,revocable:true,publicSafe:true}});});
app.post('/api/evidence/:id/verification-token/:token/revoke',...allow(R.SA),(req,res)=>{const q=db.prepare('UPDATE verification_tokens SET revoked_at=? WHERE evidence_id=? AND token_hash=?').run(iso(),req.params.id,hash(req.params.token));if(!q.changes)return res.status(404).json({error:'Verification token not found.'});res.json({revoked:true});});
app.get('/api/public/verify/:token',(req,res)=>{const [payload,signature]=String(req.params.token).split('.');if(!payload||!signature||Buffer.from(signature).length!==Buffer.from(sig(payload)).length||!crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(sig(payload))))return res.status(404).json({error:'Verification token is invalid, expired, or revoked.'});let claims;try{claims=JSON.parse(Buffer.from(payload,'base64url').toString())}catch{return res.status(404).json({error:'Verification token is invalid, expired, or revoked.'})}const t=db.prepare('SELECT * FROM verification_tokens WHERE token_hash=?').get(hash(req.params.token));if(!t||t.revoked_at||t.expires_at<Date.now()||claims.exp<Date.now()||claims.evidenceId!==t.evidence_id)return res.status(404).json({error:'Verification token is invalid, expired, or revoked.'});const r=records.get(t.evidence_id);if(!r)return res.status(404).json({error:'Evidence not found.'});const x=integrity(r);res.json({verificationStatus:'VALID',evidenceId:r.id,caseReference:r.caseId,integrityVerdict:x.valid?'VALID':'COMPROMISED',auditChainValid:x.auditChainValid,reportGenerationTime:claims.reportGeneratedAt,expiresAt:new Date(t.expires_at).toISOString(),notice:'Read-only safe verification. No raw evidence, identity, IP, device or custody data is exposed.'});});
app.get('/api/evidence/:id/report.pdf',...allow(R.FA,R.SA,R.CV),readable,(req,res)=>{const p=report(req.record),text=`Sakshya Forensic Report\\nEvidence: ${p.evidence.id}\\nIntegrity: ${p.integrityAssessment.overallValid?'VALID':'COMPROMISED'}\\nRisk: ${p.evidence.riskScore.band} (${p.evidence.riskScore.score})\\nGenerated: ${p.generatedAt}`.replace(/[()\\\\]/g,'');const pdf=`%PDF-1.4\\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\\n2 0 obj<</Type/Pages/Count 1/Kids[3 0 R]>>endobj\\n3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Resources<</Font<</F1 4 0 R>>>>/Contents 5 0 R>>endobj\\n4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\\n5 0 obj<</Length ${text.length+45}>>stream\\nBT /F1 12 Tf 50 740 Td (${text.replace(/\\n/g,') Tj 0 -18 Td (')}) Tj ET\\nendstream endobj\\ntrailer<</Root 1 0 R>>\\n%%EOF`;res.type('application/pdf').set('Content-Disposition',`inline; filename="${req.record.id}-forensic-report.pdf"`).send(pdf);});
app.post('/api/physical-tags',...allow(R.IO,R.AD),(req,res)=>{const b=req.body||{},tag=clean(b.physicalTagId),evidenceId=clean(b.evidenceId);if(!tag||!evidenceId||!records.has(evidenceId)||!clean(b.sealPackageIdentifier)||!clean(b.location))return res.status(400).json({error:'physicalTagId, existing evidenceId, sealPackageIdentifier and location are required.'});const d={physical_tag_id:tag,evidence_id:evidenceId,seal_identifier:clean(b.sealPackageIdentifier),location:clean(b.location),status:'ACTIVE',created_at:iso(),updated_at:iso(),created_by:req.actor.id};try{db.prepare('INSERT INTO physical_evidence_tags(physical_tag_id,evidence_id,seal_identifier,location,status,created_at,updated_at,created_by) VALUES(?,?,?,?,?,?,?,?)').run(d.physical_tag_id,d.evidence_id,d.seal_identifier,d.location,d.status,d.created_at,d.updated_at,d.created_by)}catch{return res.status(409).json({error:'Physical tag already exists.'})}const r=records.get(evidenceId);append(r,{action:'VIEWED',...actor(req),details:`Physical evidence tag ${tag} linked to custody record.`,location:d.location});save(r);res.status(201).json(d);});
app.get('/api/physical-tags',...allow(...READ),(_req,res)=>res.json(db.prepare('SELECT physical_tag_id,evidence_id,seal_identifier,location,status,created_at,updated_at FROM physical_evidence_tags ORDER BY created_at DESC').all()));
app.get('/api/physical-tags/:tag',...allow(...READ),(req,res)=>{const d=db.prepare('SELECT physical_tag_id,evidence_id,seal_identifier,location,status,created_at,updated_at FROM physical_evidence_tags WHERE physical_tag_id=?').get(req.params.tag);if(!d)return res.status(404).json({error:'Physical tag not found.'});const r=records.get(d.evidence_id);if(r){append(r,{action:'VIEWED',...actor(req),details:`Authorised physical QR/tag lookup: ${d.physical_tag_id}.`,location:d.location});captureNetwork(req,r.id,'PHYSICAL_TAG_LOOKUP');save(r)}res.json(d);});
app.post('/api/evidence/:id/sync-actions',...allow(R.IO,R.SA),readable,(req,res)=>{const actions=Array.isArray(req.body?.actions)?req.body.actions:[];if(!actions.length)return res.status(400).json({error:'actions must be a non-empty array.'});const out=[];for(const a of actions){const actionId=clean(a.actionId),type=clean(a.actionType).toUpperCase(),seq=Number(a.sequenceNumber);if(!actionId||!Number.isInteger(seq)||!['VIEWED','COURT_ACCESSED'].includes(type)){out.push({actionId,status:'REVIEW_REQUIRED',reason:'Invalid action ID, sequence, or unsupported offline action.'});continue}const old=db.prepare('SELECT action_id FROM synced_actions WHERE action_id=?').get(actionId);if(old){out.push({actionId,status:'DUPLICATE'});continue}const last=db.prepare('SELECT MAX(sequence_number) AS seq FROM synced_actions WHERE evidence_id=? AND actor_id=?').get(req.record.id,req.actor.id).seq;if(last!==null&&seq<=last){out.push({actionId,status:'CONFLICT',reason:'Sequence number is not newer than the last accepted action.'});continue}db.prepare('INSERT INTO synced_actions(action_id,evidence_id,actor_id,action_type,payload_json,sequence_number,processed_at) VALUES(?,?,?,?,?,?,?)').run(actionId,req.record.id,req.actor.id,type,JSON.stringify(a),seq,iso());append(req.record,{action:type,...actor(req),details:`Offline action ${actionId} accepted at sequence ${seq}.`,location:clean(a.location,'Offline client; authorised sync')});out.push({actionId,status:'ACCEPTED'});}captureNetwork(req,req.record.id,'OFFLINE_SYNC');save(req.record);res.json({results:out,notice:'Offline events require normal authentication and audit verification; acceptance does not make an offline client inherently trusted.'});});
app.post('/api/voice/parse',auth(),(req,res)=>{const text=clean(req.body?.text),verify=/case\s+(\d+)\s+ki\s+evidence\s+verify\s+karo/i.exec(text),report=/evidence\s+([A-Z0-9-]+)\s+ka\s+report\s+kholo/i.exec(text);if(verify)return res.json({intent:'VERIFY_EVIDENCE_BY_CASE',caseId:verify[1],requiresConfirmation:true,requiredRoles:[R.FA,R.CV],execution:'POST /api/evidence/:id/verify'});if(report)return res.json({intent:'OPEN_FORENSIC_REPORT',evidenceId:report[1],requiresConfirmation:true,requiredRoles:[R.FA,R.SA,R.CV],execution:'GET /api/evidence/:id/report'});res.status(422).json({error:'No supported safe Hindi command intent found.',supportedExamples:['Case 102 ki evidence verify karo','Evidence DOC-2026-001 ka report kholo'],notice:'Text parsing never executes sensitive actions automatically.'});});
app.use((err,_q,res,_n)=>{if(err instanceof multer.MulterError&&err.code==='LIMIT_FILE_SIZE')return res.status(413).json({error:'File exceeds the 25 MB upload limit.'});if(err instanceof multer.MulterError)return res.status(400).json({error:`Upload error: ${err.message}`});if(err instanceof SyntaxError&&'body'in err)return res.status(400).json({error:'Invalid JSON request body.'});console.error(err);res.status(500).json({error:'Internal server error.'});});
seed();load();app.listen(PORT,()=>console.log(`Sakshya backend listening on http://localhost:${PORT} · SQLite records: ${records.size}`));
